NCAR/wrf_hydro_training

lessons/Lesson-S3-calibration.ipynb
This is a new Jupyter notebook to work within the calibration demo Docker container. This notebook will run 10 calibration iterations for one of the gages within the Croton domain.
=> Adding calibration Jupyter notebook

lessons/training/Lesson-0-start.ipynb, lessons/training/Lesson-1-compile.ipynb, lessons/training/Lesson-2-run.ipynb, lessons/training/Lesson-3-visualize.ipynb, lessons/training/Lesson-4-run-options.ipynb
I have checked lesson 0, 1, 2 and 3 and updated those. From lesson 4, I have updated the first two experiment (warm vs cold and supplemental precip) that I was responsible for it.
=> Rfc training

lessons/training/Lesson-1-compile.ipynb
This link https://hub.docker.com/r/wrfhydro/training/ will need to change to what the url will be.
=> changed text and commands to relate to nwm

lessons/training/Lesson-2-run.ipynb
Note to remove 
params.txt
script_forcing_subset.txt
script_forcing_subset.txt_NWM_REALTIME
from the DOMAIN directory.
also, I removed the old fig2.png 
I sent Katelyn a new one to upload since I don't have permissions.
=> test edits

lessons/training/Lesson-3-visualize.ipynb
note: I'm not sure but I think the time dimension is 455 hence the statement correction. Let me know if I'm wrong.
=> Lesson 3 text edits

lessons/training/Lesson-S2-subsetting.ipynb
also a note for Arezoo (if there is time, add a legend to the figures of the channel network and LSM & hydro grids)
=> Lesson-S2 text edits

lessons/training/Lesson-6b-timeslice-generation.ipynb
I accidentally removed this because of some confusion over numbering.  Adding it back in.
=> Add back in Lesson 6b

lessons/training/Lesson-5a-land-surface.ipynb, lessons/training/Lesson-6-Channel-And-Lake.ipynb
Redo earlier PR for Lesson 6 missing filenames in ncap command, minor cleanup. Add in default hydrograph plot to Lesson 5a.
=> Lesson 5a and 6 minor updates

lessons/internal/Lesson-coupled.ipynb
=> Remove WRF-Hydro version number from file path

lessons/training/Lesson-6-lakes.ipynb
@kafitzgerald  Can you help with the TOC again? 
For now, this will be a lakes lesson.
Please edit @mollymca where you see fit.
=> Updated Lesson 6 for June training

lessons/training/Lesson-5b-groundwater-bucket.ipynb
added a link to a reference pdf with the illustrations of terrain routing and ground water in WRF-Hydro
=> added link to reference pdf

lessons/training/Lesson-5a-land-surface.ipynb
added a link to a pdf of slides that illustrated the terrain routing and ground water subjects
=> added reference link to pdf

lessons/internal/Lesson-coupled.ipynb
Per suggestion from @mollymca remove contractions from the text.
=> Coupled lesson - updates to text

lessons/training/Lesson-6-lakes.ipynb
added pdf link to reference material regarding channel routing and lakes
Guessing it's ok to have the channel info in there.
=> added pdf link  to reference material

lessons/training/Lesson-6-lakes.ipynb
I think I messed this up and did it twice, but essentially I am intending to flip Expt 1 and 2.  I think it ended up correct :)
=> Changing order of lesson 6

lessons/training/Lesson-S1-domain-initial-conditions.ipynb
removed the word "command" from the command
=> edited the pull command

lessons/training/Lesson-5-land-surface.ipynb
=> fixed file paths to DOMAIN and Restarts

lessons/training/Lesson-5-land-surface.ipynb
=> fix typo in file path

lessons/training/Lesson-0-start.ipynb, lessons/training/Lesson-1-compile.ipynb, lessons/training/Lesson-2-run.ipynb, lessons/training/Lesson-3-visualize.ipynb, lessons/training/Lesson-4-run-options.ipynb, lessons/training/Lesson-5-land-surface.ipynb, lessons/training/Lesson-S1-domain-initial-conditions.ipynb, lessons/training/Lesson-S2-regridding.ipynb
Add copyright to lessons per request from @mollymca
=> Add copyright to lessons - Costa Rica

Readme.md
change Jupyter Notebook server to Jupyter Lab server
added code version
=> minor text changes

Lesson-7-configurations.ipynb, lessons/training/Lesson-6-lakes.ipynb
=> Updates to lesson 7

lessons/training/Lesson-7-configurations.ipynb
I might not have the syntax write I was trying to add  
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
=> added summary text & panda fix

lessons/training/Lesson-S1-wps.ipynb
This PR includes changes to all lessons, mostly to the header. For GIS specific lessons, and lessons which plot hydrographs, the gage IDs and feature_id values to use have been altered. Also, tables are added for USGS gage information purposes.
=> Updated WPS lesson with new WRF-Hydro logo, gage and feature_id edits, and Pocono GIS file locations/names.

lessons/training/Lesson-0-start.ipynb, lessons/training/Lesson-1-compile.ipynb, lessons/training/Lesson-2-run.ipynb, lessons/training/Lesson-3-visualize.ipynb, lessons/training/Lesson-4-run-options.ipynb, lessons/training/Lesson-5-land-surface.ipynb, lessons/training/Lesson-6-lakes.ipynb, lessons/training/Lesson-7-configurations.ipynb, lessons/training/Lesson-S1-wps.ipynb, lessons/training/Lesson-S2-GIS-pre-processing.ipynb, lessons/training/Lesson-S3-regridding.ipynb
The previous pull-request contains the correct information for this change. Updates include new WRF-Hydro logo banners, some tables that contain gage information for USGS and NWM, and better ease of use for multiple test-cases.
=> Updates to include WRF-Hydro logo, support multiple test cases, and other USGS gages

lessons/training/Lesson-2-run.ipynb, lessons/training/Lesson-4-run-options.ipynb, lessons/training/Lesson-5-land-surface.ipynb, lessons/training/Lesson-6-lakes.ipynb, lessons/training/Lesson-7-configurations.ipynb, lessons/training/Lesson-S3-regridding.ipynb
During testing of the training in the cloud container environment, a few issues were noted. python 2 is now used to run the esmf forcing script (previously called with python3). Also, the hard-coded t=0 date for certain plots were changed to time index 0, and some gage plotting options were changed in the Lake lesson.
=> Fixes to get training working in the container on EC2

lessons/training/Lesson-0-start.ipynb
=> Removed text unrelated to this project

lessons/Lesson-5-land-surface.ipynb, lessons/Lesson-6-lakes.ipynb
=> Lessons 5&6_Nina
